name: Trivy Scan Workflow
run-name: Trivy Scan Workflow by @${{ github.actor }}

# We want to run our scan on all pushes.
on:
  push:
    branches:
      - "*"

jobs:

  # ============= #
  #   SAST SCAN   #
  # ============= #

  # This job scans our working directory prior to building a Docker image to ensure that the repository's contents
  # is as safe as possible before exposing an image to your image registry.

  trivy-sast-scan:
    runs-on: ubuntu-24.04

    env:
      TRIVY_VERSION: 0.53.0

    permissions:
      contents: read  # Permissions to read the GitHub Repository.

    steps:

      # Installs Trivy on host runner. NOTE: Sudo is required here, GitHub actions use passwordless sudo.
      - name: Install Trivy
        run: |
          sudo apt update
          wget -q https://github.com/aquasecurity/trivy/releases/download/v${TRIVY_VERSION}/trivy_${TRIVY_VERSION}_Linux-64bit.deb
          sudo dpkg -i trivy_${TRIVY_VERSION}_Linux-64bit.deb
          echo "TODO: Cache Trivy Database"

      - name: Trivy File System Scan
        run: |
          trivy fs --scanners misconfig ${{ github.workspace }} --format sarif -o trivy-scan.sarif

          echo "Constructing payload for upload to GitHub."
          echo '{"commit_sha":"${{ github.sha }}","ref":"${{ github.ref }}","sarif":"'$(gzip -c trivy-scan.sarif | base64 -w0)'"}' > sarif_payload.json

          echo "Uploading SARIF payload to GitHub."
          wget --method=POST \
            --header "Accept: application/vnd.github.v3+json" \
            --header "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --header "Content-Type: application/json" \
            --body-file=sarif_payload.json \
            --content-on-error \
            "https://api.github.com/repos/${{ github.repository }}/code-scanning/sarifs"

          echo "TODO: Fail on Criticals"

      - name: Upload Sarif Results
        run: |
          echo "TODO: Upload Sarif Results"